### ISSUE TITLE
Errno 2

### ISSUE THREAD

**Issue by vidalcenter** [Patent2net/P2N-Docker#1]
Does anyone know how to solve this error that appeared on the Mac?

NotADirectoryError: [Errno 20] Not a directory: 'DATA'

**Comment by vidalcenter** [comment]
> Does anyone know how to solve this error that appeared on the Mac?
> 
> FileNotFoundError: [Errno 2] No such file or directory: './RequestsSets/lentille.cql'

**Comment by Patent2net** [comment]
This should be ok now.
